### ISSUE TITLE
CLOUD - release_notes_2_4.md

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_cloud#1]
release_notes_2_4.md

**Comment by sasha-astiadi** [comment]
whoever is going to update it on wiki @samtaggart @Vilnite here is the 2.4 release note on manual https://manual2.threefold.io/#/release_notes_2.4.0

**Comment by samtaggart** [comment]
Thanks @sasha-astiadi I already added it to the post from today as requested

**Comment by despiegk** [comment]
all release notes are now moved to threefold wiki (the main one), its not part of sdk
