### ISSUE TITLE
Add requirement in the DGB wiki: minimum Platinum package for the VDC

### ISSUE THREAD

**Issue by BenjellounO** [threefoldfoundation/info_cloud#15]
in order to deploy a DGB node on the VDC and make it work smoothly, it is required to have at least the Platinum package for the VDC.

this requirement needs to be added to the DGB solution wiki: https://threefold.io/info/cloud#/cloud__evdc_digibyte, for people to know this before they deploy their VDC

**Comment by samtaggart** [comment]
@Sacha96 Can you handle this today? If not, I can probably do it. It's a quick note on the DigiByte section in cloud wiki.

**Comment by samtaggart** [comment]
Or before Sunday @Sacha96

**Comment by abdulgig** [comment]
@BenjellounO , just confirmed from DGB that for compute we should have 4cpu/8gb mem 

Thus, VDC should be platinum or diamond as anything less would be inadequate. The flavors in the chatflow would be adjusted accordingly also.

**Comment by BenjellounO** [comment]
@abdulgig noted, thanks for that man! @samtaggart so minimum platinum, i updated the issue.

**Comment by Sacha96** [comment]
I'm on the wiki can do it today

**Comment by Sacha96** [comment]
added change in cloud wiki review. closing story, should be live when branch is merged.
