### ISSUE TITLE
Errors on wiki to fix asap

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/info_cloud#26]
<img width="777" alt="Screenshot 2021-05-21 at 19 32 38" src="https://user-images.githubusercontent.com/54844940/119162564-d1866180-ba5a-11eb-8254-1d5db9428a12.png">

<img width="433" alt="Screenshot 2021-05-21 at 19 33 25" src="https://user-images.githubusercontent.com/54844940/119162629-e4993180-ba5a-11eb-8a76-e90983bf157d.png">

**Comment by Vilnite** [comment]
Get started page udpated:
<img width="830" alt="Screenshot 2021-05-24 at 12 58 55" src="https://user-images.githubusercontent.com/20182572/119323734-16dfa480-bc90-11eb-9663-c0a3c3213e18.png">

Current release added:
<img width="1130" alt="Screenshot 2021-05-24 at 12 59 43" src="https://user-images.githubusercontent.com/20182572/119323773-1f37df80-bc90-11eb-88b9-9a98322ecbd7.png">

<img width="1117" alt="Screenshot 2021-05-24 at 12 59 27" src="https://user-images.githubusercontent.com/20182572/119323789-22cb6680-bc90-11eb-8ecf-a51fcf043d20.png">
