### ISSUE TITLE
cleanup farming_technical

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_cloud#4]
/Users/despiegk/codewww/github/threefoldfoundation/info_foundation_archive/src/farming_technical

do it in line with 2.5

**Comment by VonSub** [comment]
I think all more tech stuff is moved over, but will do another sweep tomorrow.

**Comment by VonSub** [comment]
we'll have a call about this tomorrow.

**Comment by VonSub** [comment]
Call feel through. Checking with K if we still need to jump on.
