### ISSUE TITLE
CLOUD - socat tcp proxy way how to use planetary fs

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_cloud#5]
- use #1022
- 2 versions of zstor config in evdc (internal / external)
- for internal (in evdc) when deploying evdc we have the socat proxies setup for each zdb
- documentation on cloud_info...

**Comment by xmonader** [comment]
there're step by step scenarios documented in the issue https://github.com/threefoldtech/js-sdk/issues/2262 and also as this feature is quite interesting to geert and weynand I assigned them :)

**Comment by weynandkuijpers** [comment]
Will have a look / deploy today
