### ISSUE TITLE
CLOUD WIKI: Good enough

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_cloud#6]
We need to get the cloud wiki good enough by end of this week

**Comment by gmachtel** [comment]
In better shape now: 
- no more errors
- structure updated

Known remaining issues: 
- in unique benefits / decentralized ( https://github.com/threefoldfoundation/info_cloud/blob/development/src/usp/usp_decentralized.md ) there are a few remarks on linking to blog, add picture. @samtaggart 
- marketplace solutions deploy manual yet to be described for some solutions @gmachtel 
- release note for 2.5 to be added @sasha-astiadi 
- link to add in 'get started - where to get tokens' to wikis on 'how to buy TFTs' @gmachtel

**Comment by samtaggart** [comment]
I handled my item referenced in @gmachtel comment. Agree the wiki is looking good. Once it's "done" I am happy to review the full thing.

**Comment by samtaggart** [comment]
I think this is good enough indeed. We can review and make adjustments in the coming weeks.
