### ISSUE TITLE
TF MANUAL - Manual on setup of VDC provider 

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_cloud#9]
We need a manual for a VDC provider to be set up: 

In there, 

- [x] How to add public IPv4 addresses in Farmer Mgmt GUI or through SDK
- [ ] How to add a farm/node as a VDC provider offering

**Comment by weynandkuijpers** [comment]
Need to aim to get this done before the end of the sprint for release web_2.5.3.    I f possible 2.5.2 but I leave that to Geert to put it into this weeks sprint of he believes this can be done.

**Comment by gmachtel** [comment]
I understood cloud wiki is about usage from a user's perspective. This is more a 'farming' topic, no ?

**Comment by gmachtel** [comment]
As for now, blocked. If I understood well, new VDC providers need to be approved anyway. 
We can describe the steps once it's clear that this is a self-service process. 
Steps: 
people will have to do 
1- two wallets vdc_init, grace_period, activation_wallet
2- if you want to use other farms change manually in sals/vdc/size.py
3- vdc package change in package.toml the domain to your vdc website domain

**Comment by weynandkuijpers** [comment]
@gmachtel Let's review the current state of play with regards to documentation.

**Comment by gmachtel** [comment]
This issue was not blocked for technical issues, but reason is it's unclear on whether we should document for now, as it was mentioned that VDC need to go through an approval process. The process is not clear to me for the moment, so I can't document it.
